### PR TITLE
Relax initial local search criteria

### PR DESCRIPTION
**Pull request by hlinhn**
During initialization, instead of doing global search (which sends fast_correlative_scan_matcher only rotation information), do local search with a larger window instead. 
Previous behavior can be restored by changing
- POSE_GRAPH.global_constraint_search_starting_trajectory to 10
- POSE_GRAPH.constraint_builder.starting_new_trajectory_index to a number < 0

### CODE REVIEW

**Comment by AlexReimann** [comment]
@Roboterbastler @georgflick 
Which one of you wants to review this? :sweat_smile:

**Comment by georgflick** [comment]
> @Roboterbastler @georgflick
> Which one of you wants to review this? sweat_smile

I can do it.

**Comment by georgflick** [comment]
I just found the time to look into this PR. Compiled and worked fine. 
Cartographer is doing then a local search instead of a full search after sending the initial pose estimation.

_Tested with:_
POSE_GRAPH.global_constraint_search_starting_trajectory = -1;                                                         
POSE_GRAPH.constraint_builder.starting_new_trajectory_index = 10;


But what's still unclear to me is, under which cases are you using other parameters? 
@hlinhn Could you maybe explain it in more detail? Thanks

**Comment by hlinhn** [comment]
By keeping this parameter `POSE_GRAPH.global_constraint_search_starting_trajectory` I was hoping we could easily revert back to the current behavior without having to recompile the package, so it's easier to test or to use that parameters in case the new behavior doesn't work as well ^^

**Comment by georgflick** [comment]
> By keeping this parameter `POSE_GRAPH.global_constraint_search_starting_trajectory` I was hoping we could easily revert back to the current behavior without having to recompile the package, so it's easier to test or to use that parameters in case the new behavior doesn't work as well ^^

That makes sense, but did you test already some other parameters? Or is it dependent from the loaded pbstream file?

**Comment by johuber** [comment]
@AlexReimann will this become irrelevant with https://github.com/enwaytech/cleansquare_ros/pull/2843 ? (did not look into it deep)

**Comment by georgflick** [comment]
> @AlexReimann will this become irrelevant with [enwaytech/cleansquare_ros#2843](https://github.com/enwaytech/cleansquare_ros/pull/2843) ? (did not look into it deep)

Not really, this PR here changes the behavior of cartographer. When cartographer initializes a new trajectory, it uses local search to find constrains, instead of doing a global search, as far as I understood this PR.

**Comment by AlexReimann** [comment]
As far as I can see this does two things:

1. Add a parameter for `global_constraint_search_starting_trajectory`, which is anyways a good idea

2. Seems to try to do something we already have?
You probably want to restrict the search area during startup?
This should be already done, as you can see in `FastCorrelativeScanMatcher3D::MatchFullSubmap`:

https://github.com/enwaytech/cartographer/blob/1c886c5a069b6b204579850d629e9c0293973843/cartographer/mapping/internal/3d/scan_matching/fast_correlative_scan_matcher_3d.cc#L172-L191

If you check the this logic we shouldn't be going into local constraint matching during initialization:
https://github.com/enwaytech/cartographer/blob/962401f73002ab31278473c31cd8348db81b4a5e/cartographer/mapping/internal/3d/pose_graph_3d.cc#L268-L306

(`MaybeAddGlobalConstraint` leads to `MatchFullSubmap` being called)

**Comment by hlinhn** [comment]
> That makes sense, but did you test already some other parameters? Or is it dependent from the loaded pbstream file?

ah, sorry I thought you meant the parameters in this repo only! the other parameters (`linear_xy_search_window_initial` for example) depend on the pbstream file and the sensor, as you said.

> If you check the this logic we shouldn't be going into local constraint matching during initialization:

In my commit `global_constraint_search_starting_trajectory` < 0 will make `initialization`  `False` and thus we won't go into global search (unless we set `global_constraint_search_after_n_seconds`, which we are not doing currently)
https://github.com/enwaytech/cartographer/blob/1c886c5a069b6b204579850d629e9c0293973843/cartographer/mapping/internal/3d/pose_graph_3d.cc#L275-L279

>  This should be already done, as you can see in FastCorrelativeScanMatcher3D::MatchFullSubmap:

Because `MatchFullSubmap` only uses `global_node_rotation` and `global_submap_rotation`, `GenerateDiscreteScans` would only be sending zero translation to `DiscretizeScan`, which would match well if (I think) the submap is close enough to node's origin
https://github.com/enwaytech/cartographer/blob/1c886c5a069b6b204579850d629e9c0293973843/cartographer/mapping/internal/3d/scan_matching/fast_correlative_scan_matcher_3d.cc#L272-L276
What I aimed for here is to relax this requirement by using local search, which sends position information as well
https://github.com/enwaytech/cartographer/blob/1c886c5a069b6b204579850d629e9c0293973843/cartographer/mapping/internal/3d/pose_graph_3d.cc#L293-L296

**Comment by AlexReimann** [comment]
bump @georgflick

**Comment by adivardi** [comment]
@georgflick it's been more than a month, any update? 
This PR is standing between us and a fully running develop...

**Comment by georgflick** [comment]
> @georgflick it's been more than a month, any update?
> This PR is standing between us and a fully running develop...

Sorry for the delay :-/ I have been on vacation. Will have a look again today or monday.

**Comment by georgflick** [comment]
Like I said in an older comment I tested it already with these parameters:
```
Tested with:
POSE_GRAPH.global_constraint_search_starting_trajectory = -1;
POSE_GRAPH.constraint_builder.starting_new_trajectory_index = 10;
```
but that leads to the same behavior as before. 

@hlinhn Could you write me some other set of parameter values, which leads to the changed behavior? I guess _global_constraint_search_starting_trajectory_ should be then >0 ? What is then the expected behavior? I would be happy if you could provide more testing steps and expected behaviors :)

**Comment by hlinhn** [comment]
My test is usually: (set robot serial to `2-B-0`, maps to `cetran` branch)
1. `roslaunch enway_bringup load_parameters.launch`
2. `roscd donner_description/launch && roslaunch donner_description.launch.xml`
3. `rosrun robot_state_publisher robot_state_publisher`
4. `roslaunch enway_localization localization.launch`
5. `ewvisualization`

Run the bag file included in [this folder](https://drive.google.com/drive/folders/13jwTDYC7mQPToYQ1A6L9lXuen5e2JmKj?usp=sharing) and occasionally send initial pose through Rviz (ground truth pose is visualized in the image included in the folder, ground truth (cartographer pose) is included in `10kma.bag`). Observe that with this fix the chance that cartographer converges increases (it can converge with more points along the route and a little faster, though I have not figured out how to measure this well because it depends on the point which the pose is sent as well - we have observed (not in this bag) that some places still pose a challenge even with this fix).
I have only ever tested this on Donner so if you can suggest a good map to test this for Blitz (maybe a map where Blitz has trouble initializing in a few places?) I could try it out too.

**Comment by georgflick** [comment]
> My test is usually: (set robot serial to `2-B-0`, maps to `cetran` branch)
> 
>     1. `roslaunch enway_bringup load_parameters.launch`
> 
>     2. `roscd donner_description/launch && roslaunch donner_description.launch.xml`
> 
>     3. `rosrun robot_state_publisher robot_state_publisher`
> 
>     4. `roslaunch enway_localization localization.launch`
> 
>     5. `ewvisualization`
> 
> 
> Run the bag file included in [this folder](https://drive.google.com/drive/folders/13jwTDYC7mQPToYQ1A6L9lXuen5e2JmKj?usp=sharing) and occasionally send initial pose through Rviz (ground truth pose is visualized in the image included in the folder, ground truth (cartographer pose) is included in `10kma.bag`). Observe that with this fix the chance that cartographer converges increases (it can converge with more points along the route and a little faster, though I have not figured out how to measure this well because it depends on the point which the pose is sent as well - we have observed (not in this bag) that some places still pose a challenge even with this fix).
> I have only ever tested this on Donner so if you can suggest a good map to test this for Blitz (maybe a map where Blitz has trouble initializing in a few places?) I could try it out too.

Thanks! 
And which parameter values make sense to test? (POSE_GRAPH.global_constraint_search_starting_trajectory and 
POSE_GRAPH.constraint_builder.starting_new_trajectory_index)

**Comment by hlinhn** [comment]
> > My test is usually: (set robot serial to `2-B-0`, maps to `cetran` branch)
> > ```
> > 1. `roslaunch enway_bringup load_parameters.launch`
> > 
> > 2. `roscd donner_description/launch && roslaunch donner_description.launch.xml`
> > 
> > 3. `rosrun robot_state_publisher robot_state_publisher`
> > 
> > 4. `roslaunch enway_localization localization.launch`
> > 
> > 5. `ewvisualization`
> > ```
> > 
> > 
> > Run the bag file included in [this folder](https://drive.google.com/drive/folders/13jwTDYC7mQPToYQ1A6L9lXuen5e2JmKj?usp=sharing) and occasionally send initial pose through Rviz (ground truth pose is visualized in the image included in the folder, ground truth (cartographer pose) is included in `10kma.bag`). Observe that with this fix the chance that cartographer converges increases (it can converge with more points along the route and a little faster, though I have not figured out how to measure this well because it depends on the point which the pose is sent as well - we have observed (not in this bag) that some places still pose a challenge even with this fix).
> > I have only ever tested this on Donner so if you can suggest a good map to test this for Blitz (maybe a map where Blitz has trouble initializing in a few places?) I could try it out too.
> 
> Thanks!
> And which parameter values make sense to test? (POSE_GRAPH.global_constraint_search_starting_trajectory and
> POSE_GRAPH.constraint_builder.starting_new_trajectory_index)

ah, I think I misunderstood your question earlier. The changed behaviour is with the default parameters set in this PR (`POSE_GRAPH.global_constraint_search_starting_trajectory` < 0 and `POSE_GRAPH.constraint_builder.starting_new_trajectory_index` > 0, set to 10), so probably the set you already tested?

**Review by georgflick — APPROVED** [review]
Code looks fine to me.
Tested with blitz one in drivery courtyard map:

Measurments:
```
Measured time needed to localize (simulation with courtyard map):
without PR: 45 - 70 seconds
with the PR: 8 - 37 seconds
with PR and starting_new_trajectory_index = -1 and global_constraint_search_starting_trajectory 10 (which is the same like the old behavior):
46s - 70s
```

It is a nice improvement for the localization in terms of speed. Nice work @hlinhn

**Review by AlexReimann — APPROVED** [review]

**Comment by AlexReimann** [comment]
Need to toggle a new cartographer package rollout after merge

**Comment by hlinhn** [comment]
Forced push to sign commit

**Pull request merged**
